# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{haithermo}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Karl Smith"]
  s.date = %q{2010-03-18}
  s.description = %q{A ruby library that implements the HAI Omnistat Thermostat protocol}
  s.email = %q{threadhead@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "HAI Omnistat Serial Protocol r4-98C.pdf",
     "HAIthermo.gemspec",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "hai_thermo.rb",
     "lib/control.rb",
     "lib/logger.rb",
     "lib/message_factory.rb",
     "lib/messages/base.rb",
     "lib/messages/poll_for_group1_data.rb",
     "lib/messages/poll_for_group2_data.rb",
     "lib/messages/poll_for_registers.rb",
     "lib/messages/receive_ACK.rb",
     "lib/messages/receive_NACK.rb",
     "lib/messages/receive_data.rb",
     "lib/messages/receive_group1_data.rb",
     "lib/messages/receive_group2_data.rb",
     "lib/messages/set_registers.rb",
     "lib/thermostat.rb",
     "lib/thermostat/actions.rb",
     "lib/thermostat/base.rb",
     "lib/thermostat/display_options.rb",
     "lib/thermostat/fixnum_bits.rb",
     "lib/thermostat/output_status.rb",
     "lib/thermostat/register.rb",
     "lib/thermostat/register_bits.rb",
     "no_longer_used/hold_test_thermostat_schedules.rb",
     "no_longer_used/hold_test_timestamp_attribute.rb",
     "no_longer_used/schedule.rb",
     "no_longer_used/timestamp_attribute.rb",
     "test.rb",
     "test/test_fixnum_bits.rb",
     "test/test_helper.rb",
     "test/test_message.rb",
     "test/test_message_factory.rb",
     "test/test_registers.rb",
     "test/test_thermostat_base.rb"
  ]
  s.homepage = %q{http://github.com/threadhead/haithermo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A ruby library that implements the HAI Omnistat Thermostat protocol}
  s.test_files = [
    "test/test_fixnum_bits.rb",
     "test/test_helper.rb",
     "test/test_message.rb",
     "test/test_message_factory.rb",
     "test/test_registers.rb",
     "test/test_thermostat_base.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

