require 'lib/thermostat/register/read_only'
require 'lib/thermostat/register/base'
require 'lib/thermostat/register/reserved'
require 'lib/thermostat/register/temperature'
require 'lib/thermostat/register/time'
